//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WOCosting
{
    using System;
    using System.Collections.Generic;
    
    public partial class TASWOCostAppLog
    {
        public long TASWOCostLog_ID { get; set; }
        public string WONumber { get; set; }
        public bool Result { get; set; }
        public System.DateTime DateRan { get; set; }
    }
}
