//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WOCosting
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorksOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WorksOrder()
        {
            this.WorksOrderTransfers = new HashSet<WorksOrderTransfer>();
        }
    
        public string WorksOrderNumber { get; set; }
        public short IncompleteTransfers { get; set; }
        public int PartID { get; set; }
        public int MethodID { get; set; }
        public int VersionID { get; set; }
        public decimal BatchQuantity { get; set; }
        public Nullable<decimal> QuantityStored { get; set; }
        public System.DateTime CompletionDate { get; set; }
        public string SalesOrderNumber { get; set; }
        public Nullable<short> LineNumber { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<decimal> UnitThroughputValue { get; set; }
        public Nullable<decimal> UnitSellingPrice { get; set; }
        public string IssueNotes { get; set; }
        public string SalesNotes { get; set; }
        public string ProgrammeNumbers { get; set; }
        public short WorksOrderCostStatusCode { get; set; }
        public decimal PlannedMaterialCost { get; set; }
        public decimal PlannedSubcontractCost { get; set; }
        public decimal PlannedRunCost { get; set; }
        public decimal PlannedSetCost { get; set; }
        public System.DateTime PlannedDateSet { get; set; }
        public Nullable<decimal> ActualMaterialCost { get; set; }
        public Nullable<decimal> ActualSubcontractCost { get; set; }
        public Nullable<decimal> ActualRunCost { get; set; }
        public Nullable<decimal> ActualSetCost { get; set; }
        public Nullable<decimal> ActualLabourHours { get; set; }
        public Nullable<System.DateTime> ActualDateSet { get; set; }
        public bool IsManualLink { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public Nullable<int> PartIssueID { get; set; }
        public Nullable<int> ResponsibilityCodeID { get; set; }
        public int WorksOrderTypeID { get; set; }
        public Nullable<bool> WOEnactedFromMRP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorksOrderTransfer> WorksOrderTransfers { get; set; }
    }
}
